apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-cache
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: {{ .Values.storage_class }}
